/* Generated By:JavaCC: Do not edit this line. TokenSequenceParser.java */
package edu.stanford.nlp.ling.tokensregex;
// all generated classes are in this package

//imports
import edu.stanford.nlp.util.CoreMap;
import edu.stanford.nlp.util.ArrayMap;
import edu.stanford.nlp.util.Pair;
import java.io.Reader;
import java.io.StringReader;
import java.util.*;

class TokenSequenceParser implements SequencePattern.Parser<CoreMap>, TokenSequenceParserConstants {
    TokenSequenceParser() {}

    public CoreMapExpressionExtractor getExpressionExtractor(TokenSequencePattern.Env env, Reader r) throws ParseException {
        TokenSequenceParser p = new TokenSequenceParser(r);
        List<SequenceMatchRules.Rule> rules = p.RuleList(env);
        return new CoreMapExpressionExtractor(env, rules);
    }

    public void updateExpressionExtractor(CoreMapExpressionExtractor extractor, Reader r) throws ParseException {
        TokenSequenceParser p = new TokenSequenceParser(r);
        List<SequenceMatchRules.Rule> rules = p.RuleList(extractor.env);
        extractor.appendRules(rules);
    }

        public SequencePattern.PatternExpr parseSequence(TokenSequencePattern.Env env, String s) throws ParseException {
        TokenSequenceParser p = new TokenSequenceParser(new StringReader(s));
        return p.SeqRegex(env);
        }

        public Pair<SequencePattern.PatternExpr, SequenceMatchAction<CoreMap>> parseSequenceWithAction(TokenSequencePattern.Env env, String s) throws ParseException {
        TokenSequenceParser p = new TokenSequenceParser(new StringReader(s));
        return p.SeqRegexWithAction(env);
        }

        public SequencePattern.PatternExpr parseNode(TokenSequencePattern.Env env, String s) throws ParseException {
        TokenSequenceParser p = new TokenSequenceParser(new StringReader(s));
        NodePattern n = p.Node(env);
        return new SequencePattern.NodePatternExpr(n);
        }

    private Integer parseInteger(String str) {
      if (str.startsWith("+")) {
        return Integer.valueOf(str.substring(1));
      } else {
        return Integer.valueOf(str);
      }
    }

  final public List<SequenceMatchRules.Rule> RuleList(SequencePattern.Env env) throws ParseException {
  List<SequenceMatchRules.Rule> rules = new ArrayList<SequenceMatchRules.Rule>();
  SequenceMatchRules.Rule rule;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case 18:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      rule = Rule(env);
                         rules.add(rule);
    }
      {if (true) return rules;}
    throw new Error("Missing return statement in function");
  }

  final public SequenceMatchRules.Rule Rule(SequencePattern.Env env) throws ParseException {
  SequenceMatchRules.Rule rule;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 18:
      rule = ExpressionExtractorRule(env);
      break;
    case IDENTIFIER:
      rule = AssignmentRule(env);
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return rule;}
    throw new Error("Missing return statement in function");
  }

  final public SequenceMatchRules.Rule ExpressionExtractorRule(SequencePattern.Env env) throws ParseException {
  SequencePattern.PatternExpr expr;
  String stringRegex;
  SequenceMatchRules.Expression result;
  Token ruleTypeToken;
    if (jj_2_1(2)) {
      jj_consume_token(18);
      expr = SeqRegex(env);
      jj_consume_token(19);
      result = Expression(env);
      jj_consume_token(20);
    {if (true) return SequenceMatchRules.createTokenPatternRule(env, expr, result);}
    } else if (jj_2_2(2)) {
      jj_consume_token(18);
      jj_consume_token(21);
      expr = SeqRegex(env);
      jj_consume_token(19);
      result = Expression(env);
      jj_consume_token(20);
    {if (true) return SequenceMatchRules.createTokenPatternRule(env, expr, result);}
    } else if (jj_2_3(2)) {
      jj_consume_token(18);
      jj_consume_token(22);
      stringRegex = StringRegex(env);
      jj_consume_token(19);
      result = Expression(env);
      jj_consume_token(20);
    {if (true) return SequenceMatchRules.createTextPatternRule(env, stringRegex, result);}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public SequenceMatchRules.Rule AssignmentRule(SequencePattern.Env env) throws ParseException {
  Token varToken;
  SequenceMatchRules.Expression result;
    varToken = jj_consume_token(IDENTIFIER);
    jj_consume_token(23);
    result = Expression(env);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 24:
      jj_consume_token(24);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    {if (true) return SequenceMatchRules.createAssignmentRule(env, varToken.image, result);}
    throw new Error("Missing return statement in function");
  }

/*
List<CoreMapExpressionExtractor.Result> ResultList(SequencePattern.Env env) : {
  List<CoreMapExpressionExtractor.Result> list = new ArrayList<CoreMapExpressionExtractor.Result>();
  CoreMapExpressionExtractor.Result result;
} {
   ( result = Result(env) { list.add(result); } )
   ( "," result = Result(env)  { list.add(result); } )*
   { return list; }
}  */
  final public SequenceMatchRules.Expression Expression(SequencePattern.Env env) throws ParseException {
  SequenceMatchRules.Expression expr;
    if (jj_2_4(2)) {
      expr = FunctionExpression(env);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case REGEXVAR:
      case REGEXGROUP:
      case NONNEGINT:
      case INT:
      case REAL:
      case REGEX:
      case STR:
      case 18:
        expr = ValueExpression(env);
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return expr;}
    throw new Error("Missing return statement in function");
  }

  final public SequenceMatchRules.Expression FunctionExpression(SequencePattern.Env env) throws ParseException {
  Token typeToken;
  SequenceMatchRules.Expression param;
  List<SequenceMatchRules.Expression> params = new ArrayList<SequenceMatchRules.Expression>();
    typeToken = jj_consume_token(IDENTIFIER);
    jj_consume_token(25);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case REGEXVAR:
    case REGEXGROUP:
    case NONNEGINT:
    case INT:
    case REAL:
    case REGEX:
    case STR:
    case 18:
      param = Expression(env);
                                 params.add(param);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 26:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_2;
        }
        jj_consume_token(26);
        param = Expression(env);
                                       params.add(param);
      }
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(27);
    {if (true) return new SequenceMatchRules.FunctionExpression(typeToken.image, params);}
    throw new Error("Missing return statement in function");
  }

  final public SequenceMatchRules.Value ValueExpression(SequencePattern.Env env) throws ParseException {
  SequenceMatchRules.Value expr;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case REGEXVAR:
    case REGEXGROUP:
    case NONNEGINT:
    case INT:
    case REAL:
    case REGEX:
    case STR:
      expr = BasicValue(env);
      break;
    case 18:
      expr = CompositeFieldValue(env);
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return expr;}
    throw new Error("Missing return statement in function");
  }

  final public SequenceMatchRules.Value CompositeFieldValue(SequencePattern.Env env) throws ParseException {
    Map<String, SequenceMatchRules.Expression> attributes = new ArrayMap<String,SequenceMatchRules.Expression>();
    jj_consume_token(18);
    FieldValue(env, attributes);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 24:
      case 26:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 26:
        jj_consume_token(26);
        break;
      case 24:
        jj_consume_token(24);
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      FieldValue(env, attributes);
    }
    jj_consume_token(20);
          {if (true) return new SequenceMatchRules.CompositeValue(/*"COMPOSITE", */ attributes, false);}
    throw new Error("Missing return statement in function");
  }

  final public Map<String,SequenceMatchRules.Expression> FieldValue(SequencePattern.Env env, Map<String,SequenceMatchRules.Expression> attributes) throws ParseException {
        Token field = null;
        SequenceMatchRules.Expression expr = null;
    field = jj_consume_token(IDENTIFIER);
    jj_consume_token(28);
    expr = Expression(env);
              if (field != null && expr != null)  {
                if (attributes.containsKey(field.image)) {
                {if (true) throw new Error("Field already defined: " + field.image);}
                }
                attributes.put(field.image, expr);
              }
          {if (true) return attributes;}
    throw new Error("Missing return statement in function");
  }

  final public SequenceMatchRules.Value BasicValue(SequencePattern.Env env) throws ParseException {
        Token tok = null;
    SequencePattern.PatternExpr seqRegex;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case REGEX:
      tok = jj_consume_token(REGEX);
                        {if (true) return new SequenceMatchRules.RegexValue(/*"REGEX",*/ tok.image.substring(1,tok.image.length()-1));}
      break;
    case STR:
      tok = jj_consume_token(STR);
                      {if (true) return new SequenceMatchRules.PrimitiveValue<String>("STRING", tok.image.substring(1,tok.image.length()-1) );}
      break;
    case NONNEGINT:
    case INT:
      tok = IntegerToken();
                               {if (true) return new SequenceMatchRules.PrimitiveValue<Number>("INTEGER", parseInteger(tok.image));}
      break;
    case REAL:
      tok = jj_consume_token(REAL);
                       {if (true) return new SequenceMatchRules.PrimitiveValue<Number>("REAL", Double.valueOf(tok.image));}
      break;
    case IDENTIFIER:
      tok = jj_consume_token(IDENTIFIER);
                             {if (true) return new SequenceMatchRules.VarValue(tok.image);}
      break;
    case REGEXVAR:
      tok = jj_consume_token(REGEXVAR);
                           {if (true) return new SequenceMatchRules.RegexMatchVarValue(tok.image);}
      break;
    case REGEXGROUP:
      tok = jj_consume_token(REGEXGROUP);
                             {if (true) return new SequenceMatchRules.RegexMatchVarValue(Integer.valueOf(tok.image.substring(1)));}
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String StringRegex(SequencePattern.Env env) throws ParseException {
  Token exprToken;
    exprToken = jj_consume_token(REGEX);
                               {if (true) return exprToken.image;}
    throw new Error("Missing return statement in function");
  }

  final public SequencePattern.PatternExpr SeqRegex(SequencePattern.Env env) throws ParseException {
  SequencePattern.PatternExpr expr;
    expr = SeqRegexDisjConj(env);
                                        {if (true) return expr;}
    throw new Error("Missing return statement in function");
  }

  final public SequencePattern.PatternExpr SeqRegexBasic(SequencePattern.Env env) throws ParseException {
  List<SequencePattern.PatternExpr> children = new ArrayList<SequencePattern.PatternExpr>();
  NodePattern node;
  MultiNodePattern multiNode;
  SequencePattern.PatternExpr expr;
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 35:
        node = BracketedNode(env);
                                        expr = new SequencePattern.NodePatternExpr(node);
        break;
      case IDENTIFIER:
      case REGEX:
      case STR:
      case BARESTR:
        node = CoreMapWordPattern(env);
                                             expr = new SequencePattern.NodePatternExpr(node);
        break;
      case 39:
        multiNode = MultiNodePattern(env);
                                                expr = new SequencePattern.MultiNodePatternExpr(multiNode);
        break;
      case 25:
        expr = SeqRegexGroup(env);
        break;
      case REGEXVAR:
        expr = SeqVar(env);
        break;
      case BACKREF:
        expr = SeqBackRef(env);
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 18:
      case 29:
      case 30:
      case 31:
        expr = SeqRegexRepeatTimes(env, expr);
        break;
      default:
        jj_la1[11] = jj_gen;
        ;
      }
         children.add(expr);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case REGEXVAR:
      case BACKREF:
      case REGEX:
      case STR:
      case BARESTR:
      case 25:
      case 35:
      case 39:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_4;
      }
    }
          if (children.size() == 1) {if (true) return expr;}
          else {if (true) return new SequencePattern.SequencePatternExpr(children);}
    throw new Error("Missing return statement in function");
  }

  final public SequencePattern.PatternExpr SeqRegexRepeatTimes(SequencePattern.Env env, SequencePattern.PatternExpr expr) throws ParseException {
   Token value;
   Token v2;
   int min = -1;
   int max = -1;
   boolean greedy = true;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 29:
      value = jj_consume_token(29);
                          min = 0; max = -1;
      break;
    case 30:
      value = jj_consume_token(30);
                          min = 0; max = 1;
      break;
    case 31:
      value = jj_consume_token(31);
                          min = 1; max = -1;
      break;
    default:
      jj_la1[13] = jj_gen;
      if (jj_2_5(3)) {
        jj_consume_token(18);
        value = jj_consume_token(NONNEGINT);
        jj_consume_token(20);
                                          min = Integer.parseInt(value.image); max = min;
      } else if (jj_2_6(4)) {
        jj_consume_token(18);
        value = jj_consume_token(NONNEGINT);
        jj_consume_token(26);
        jj_consume_token(20);
                                              min = Integer.parseInt(value.image); max = -1;
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 18:
          jj_consume_token(18);
          value = jj_consume_token(NONNEGINT);
          jj_consume_token(26);
          v2 = jj_consume_token(NONNEGINT);
          jj_consume_token(20);
                                                                min = Integer.parseInt(value.image); max = Integer.parseInt(v2.image);
          break;
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 30:
      jj_consume_token(30);
             greedy = false;
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
      {if (true) return new SequencePattern.RepeatPatternExpr(expr, min, max, greedy);}
    throw new Error("Missing return statement in function");
  }

  final public SequencePattern.PatternExpr SeqRegexDisj(SequencePattern.Env env) throws ParseException {
  List<SequencePattern.PatternExpr> children = new ArrayList<SequencePattern.PatternExpr>();
  SequencePattern.PatternExpr expr;
    expr = SeqRegexBasic(env);
                                    children.add(expr);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 32:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_5;
      }
      jj_consume_token(32);
      expr = SeqRegexBasic(env);
                                         children.add(expr);
    }
            if (children.size() == 1) { {if (true) return children.get(0);} }
                else { {if (true) return new SequencePattern.OrPatternExpr(children);}  }
    throw new Error("Missing return statement in function");
  }

  final public SequencePattern.PatternExpr SeqRegexDisjConj(SequencePattern.Env env) throws ParseException {
        SequencePattern.PatternExpr child;
        List<SequencePattern.PatternExpr> disjChildren = new ArrayList<SequencePattern.PatternExpr>();
        List<SequencePattern.PatternExpr> conjChildren = new ArrayList<SequencePattern.PatternExpr>();
        Token op;
    child = SeqRegexBasic(env);
                                    conjChildren.add(child);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 32:
      case 33:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 33:
        op = jj_consume_token(33);
        break;
      case 32:
        op = jj_consume_token(32);
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      child = SeqRegexBasic(env);
             if ("&".equals(op.image)) {
              conjChildren.add(child);
             } else if ("|".equals(op.image)) {
               if (conjChildren.size() > 1) {
                  disjChildren.add(new SequencePattern.AndPatternExpr(conjChildren));
               } else {
                  disjChildren.add(conjChildren.get(0));
               }
               conjChildren = new ArrayList<SequencePattern.PatternExpr>();
               conjChildren.add(child);
             }
    }
          if (conjChildren.size() > 1) {
             disjChildren.add(new SequencePattern.AndPatternExpr(conjChildren));
          } else {
             disjChildren.add(conjChildren.get(0));
          }
          if (disjChildren.size() == 1)
                {if (true) return disjChildren.get(0);}
          else
                {if (true) return new SequencePattern.OrPatternExpr(disjChildren);}
    throw new Error("Missing return statement in function");
  }

  final public SequencePattern.PatternExpr SeqRegexGroup(SequencePattern.Env env) throws ParseException {
  SequencePattern.PatternExpr expr;
  boolean capturing = true;
  String varname = null;
  Token var;
    jj_consume_token(25);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 30:
    case 34:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 34:
        jj_consume_token(34);
                capturing = false;
        break;
      case 30:
        jj_consume_token(30);
        var = jj_consume_token(REGEXVAR);
                                varname = var.image;
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    expr = SeqRegex(env);
    jj_consume_token(27);
                if (varname != null) {
                   {if (true) return new SequencePattern.GroupPatternExpr(expr, varname);}
                } else {
                   {if (true) return new SequencePattern.GroupPatternExpr(expr, capturing);}
        }
    throw new Error("Missing return statement in function");
  }

  final public NodePattern BracketedNode(SequencePattern.Env env) throws ParseException {
  NodePattern node;
    if (jj_2_7(2)) {
      jj_consume_token(35);
      jj_consume_token(36);
              node = NodePattern.ANY_NODE;
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 35:
        jj_consume_token(35);
        node = NodeDisjConj(env);
        jj_consume_token(36);
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return node;}
    throw new Error("Missing return statement in function");
  }

  final public SequencePattern.PatternExpr SeqVar(SequencePattern.Env env) throws ParseException {
  SequencePattern.PatternExpr expr;
  Token name;
    name = jj_consume_token(REGEXVAR);
        expr = env.getSequencePatternExpr(name.image, true);
        if (expr == null) {
            {if (true) throw new Error("Unknown sequence pattern variable " + name.image);}
        }
    {if (true) return expr;}
    throw new Error("Missing return statement in function");
  }

  final public SequencePattern.PatternExpr SeqBackRef(SequencePattern.Env env) throws ParseException {
  Token name;
    name = jj_consume_token(BACKREF);
        int v = Integer.parseInt(name.image.substring(1));
        {if (true) return new SequencePattern.BackRefPatternExpr(CoreMapNodePattern.TEXT_ATTR_EQUAL_CHECKER, v);}
    throw new Error("Missing return statement in function");
  }

  final public NodePattern Node(SequencePattern.Env env) throws ParseException {
  NodePattern node;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 35:
      node = BracketedNode(env);
      break;
    case IDENTIFIER:
    case REGEXVAR:
    case REGEX:
    case STR:
    case BARESTR:
    case 18:
    case 25:
    case 37:
      node = NodeGroup(env);
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return node;}
    throw new Error("Missing return statement in function");
  }

  final public NodePattern NodeDisj(SequencePattern.Env env) throws ParseException {
        List<NodePattern> children = new ArrayList<NodePattern>();
        NodePattern child;
    child = NodeGroup(env);
                                 children.add(child);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 32:
        ;
        break;
      default:
        jj_la1[23] = jj_gen;
        break label_7;
      }
      jj_consume_token(32);
      child = NodeGroup(env);
                                        children.add(child);
    }
          if (children.size() == 1)
                {if (true) return child;}
          else
                {if (true) return new NodePattern.DisjNodePattern(children);}
    throw new Error("Missing return statement in function");
  }

  final public NodePattern NodeConj(SequencePattern.Env env) throws ParseException {
        NodePattern child;
        List children = new ArrayList();
    child = NodeGroup(env);
                                children.add(child);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 33:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_8;
      }
      jj_consume_token(33);
      child = NodeGroup(env);
                                        children.add(child);
    }
          if (children.size() == 1)
                {if (true) return child;}
          else
                {if (true) return new NodePattern.ConjNodePattern(children);}
    throw new Error("Missing return statement in function");
  }

  final public NodePattern NodeDisjConj(SequencePattern.Env env) throws ParseException {
        NodePattern child;
        List<NodePattern> disjChildren = new ArrayList<NodePattern>();
        List<NodePattern> conjChildren = new ArrayList<NodePattern>();
        Token op;
    child = NodeGroup(env);
                                conjChildren.add(child);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 32:
      case 33:
        ;
        break;
      default:
        jj_la1[25] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 33:
        op = jj_consume_token(33);
        break;
      case 32:
        op = jj_consume_token(32);
        break;
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      child = NodeGroup(env);
             if ("&".equals(op.image)) {
              conjChildren.add(child);
             } else if ("|".equals(op.image)) {
               if (conjChildren.size() > 1) {
                  disjChildren.add(new NodePattern.ConjNodePattern(conjChildren));
               } else {
                  disjChildren.add(conjChildren.get(0));
               }
               conjChildren = new ArrayList<NodePattern>();
               conjChildren.add(child);
             }
    }
          if (conjChildren.size() > 1) {
             disjChildren.add(new NodePattern.ConjNodePattern(conjChildren));
          } else {
             disjChildren.add(conjChildren.get(0));
          }
          if (disjChildren.size() == 1)
                {if (true) return disjChildren.get(0);}
          else
                {if (true) return new NodePattern.DisjNodePattern(disjChildren);}
    throw new Error("Missing return statement in function");
  }

  final public NodePattern NodeGroup(SequencePattern.Env env) throws ParseException {
  NodePattern node;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case REGEXVAR:
    case REGEX:
    case STR:
    case BARESTR:
    case 18:
    case 37:
      node = NodeBasic(env);
      break;
    case 25:
      jj_consume_token(25);
      node = NodeDisjConj(env);
      jj_consume_token(27);
      break;
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return node;}
    throw new Error("Missing return statement in function");
  }

  final public NodePattern NodeBasic(SequencePattern.Env env) throws ParseException {
        NodePattern child;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 37:
      jj_consume_token(37);
      child = CoreMapNode(env);
          {if (true) return new NodePattern.NegateNodePattern(child);}
      break;
    case IDENTIFIER:
    case REGEXVAR:
    case REGEX:
    case STR:
    case BARESTR:
    case 18:
      child = CoreMapNode(env);
          {if (true) return child;}
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodePattern CoreMapNode(SequencePattern.Env env) throws ParseException {
    Map<String, String> attributes = new ArrayMap<String,String>();
    NodePattern pat;
        Token value = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case REGEX:
    case STR:
    case BARESTR:
    case 18:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 18:
        jj_consume_token(18);
        AttrValue(env, attributes);
        label_10:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 24:
          case 26:
            ;
            break;
          default:
            jj_la1[29] = jj_gen;
            break label_10;
          }
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 26:
            jj_consume_token(26);
            break;
          case 24:
            jj_consume_token(24);
            break;
          default:
            jj_la1[30] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          AttrValue(env, attributes);
        }
        jj_consume_token(20);
        break;
      case IDENTIFIER:
      case REGEX:
      case STR:
      case BARESTR:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
        case STR:
        case BARESTR:
          value = RelaxedStringToken();
          break;
        case REGEX:
          value = jj_consume_token(REGEX);
          break;
        default:
          jj_la1[31] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                        attributes.put("word", value.image);
        break;
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          pat = CoreMapNodePattern.valueOf(env, attributes);
          {if (true) return pat;}
      break;
    case REGEXVAR:
      pat = CoreMapVarNodePattern(env);
            {if (true) return pat;}
      break;
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Map<String,String> AttrValue(SequencePattern.Env env, Map<String,String> attributes) throws ParseException {
        Token attr = null;
        Token value = null;
        Token tok = null;
        String str = null;
    attr = jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 28:
      jj_consume_token(28);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STR:
        value = jj_consume_token(STR);
        break;
      case REGEX:
        value = jj_consume_token(REGEX);
        break;
      case BARESTR:
        value = jj_consume_token(BARESTR);
        break;
      case IDENTIFIER:
        value = jj_consume_token(IDENTIFIER);
        break;
      case REGEXVAR:
        str = CoreMapVarValue(env);
        break;
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case 38:
      tok = jj_consume_token(38);
      value = jj_consume_token(IDENTIFIER);
      break;
    case NUMCMP:
      tok = jj_consume_token(NUMCMP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NONNEGINT:
      case INT:
      case REAL:
        value = NumberToken();
        break;
      case REGEXVAR:
        str = CoreMapVarValue(env);
        break;
      default:
        jj_la1[35] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
              if (value != null) { str = value.image; }
              if (tok != null) { str = tok.image + str; }
              if (attr != null && str != null)  {
                if (attributes.containsKey(attr.image)) {
                {if (true) throw new Error("Attribute match already defined: " + attr.image);}
                }
                attributes.put(attr.image, str);
              }
          {if (true) return attributes;}
    throw new Error("Missing return statement in function");
  }

  final public NodePattern CoreMapWordPattern(SequencePattern.Env env) throws ParseException {
    Map<String, String> attributes = new ArrayMap<String,String>();
    CoreMapNodePattern pat;
        Token value = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STR:
      value = jj_consume_token(STR);
      break;
    case REGEX:
      value = jj_consume_token(REGEX);
      break;
    case BARESTR:
      value = jj_consume_token(BARESTR);
      break;
    case IDENTIFIER:
      value = jj_consume_token(IDENTIFIER);
      break;
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                  attributes.put("word", value.image);
          pat = CoreMapNodePattern.valueOf(env, attributes);
          {if (true) return pat;}
    throw new Error("Missing return statement in function");
  }

  final public MultiNodePattern MultiNodePattern(SequencePattern.Env env) throws ParseException {
    NodePattern pat;
    MultiNodePattern mp;
    Token v1, v2;
    int min = 1, max = -1;
    jj_consume_token(39);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 18:
      if (jj_2_8(3)) {
        jj_consume_token(18);
        v1 = jj_consume_token(NONNEGINT);
        jj_consume_token(20);
       min = Integer.parseInt(v1.image);
       max = Integer.parseInt(v1.image);
      } else if (jj_2_9(4)) {
        jj_consume_token(18);
        v1 = jj_consume_token(NONNEGINT);
        jj_consume_token(26);
        jj_consume_token(20);
       min = Integer.parseInt(v1.image);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 18:
          jj_consume_token(18);
          v1 = jj_consume_token(NONNEGINT);
          jj_consume_token(26);
          v2 = jj_consume_token(NONNEGINT);
          jj_consume_token(20);
       min = Integer.parseInt(v1.image);
       max = Integer.parseInt(v2.image);
          break;
        default:
          jj_la1[38] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      break;
    default:
      jj_la1[39] = jj_gen;
      ;
    }
    pat = CoreMapWordPattern(env);
      mp = new MultiCoreMapNodePattern(pat);
      mp.setMinNodes(min);
      mp.setMaxNodes(max);
      {if (true) return mp;}
    throw new Error("Missing return statement in function");
  }

  final public String CoreMapVarValue(SequencePattern.Env env) throws ParseException {
        Token value = null;
    value = jj_consume_token(REGEXVAR);
                                 {if (true) return (String) env.get(value.image);}
    throw new Error("Missing return statement in function");
  }

  final public NodePattern CoreMapVarNodePattern(SequencePattern.Env env) throws ParseException {
        Token value = null;
    value = jj_consume_token(REGEXVAR);
                                 {if (true) return env.getNodePattern(value.image);}
    throw new Error("Missing return statement in function");
  }

  final public Pair<SequencePattern.PatternExpr, SequenceMatchAction<CoreMap>> SeqRegexWithAction(SequencePattern.Env env) throws ParseException {
  SequencePattern.PatternExpr expr;
  SequenceMatchAction<CoreMap> action = null;
    expr = SeqRegex(env);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 19:
      action = Action(env);
      break;
    default:
      jj_la1[40] = jj_gen;
      ;
    }
      {if (true) return new Pair<SequencePattern.PatternExpr, SequenceMatchAction<CoreMap>>(expr,action);}
    throw new Error("Missing return statement in function");
  }

  final public SequenceMatchAction<CoreMap> Action(SequencePattern.Env env) throws ParseException {
   SequenceMatchAction<CoreMap> action;
    jj_consume_token(19);
    action = AnnotateAction(env);
    {if (true) return action;}
    throw new Error("Missing return statement in function");
  }

  final public SequenceMatchAction<CoreMap> AnnotateAction(SequencePattern.Env env) throws ParseException {
  Map<String, String> attributes;
    jj_consume_token(40);
    jj_consume_token(25);
    //  group = <NONNEGINT> ","
      attributes = SetAttrValues(env);
    jj_consume_token(27);
    {if (true) return new CoreMapSequenceMatchAction.AnnotateAction<CoreMap>( /*group,*/ attributes);}
    throw new Error("Missing return statement in function");
  }

  final public Map<String,String> SetAttrValues(SequencePattern.Env env) throws ParseException {
    Map<String, String> attributes = new ArrayMap<String,String>();
    jj_consume_token(18);
    SetAttrValue(env, attributes);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 24:
      case 26:
        ;
        break;
      default:
        jj_la1[41] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 26:
        jj_consume_token(26);
        break;
      case 24:
        jj_consume_token(24);
        break;
      default:
        jj_la1[42] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      SetAttrValue(env, attributes);
    }
    jj_consume_token(20);
          {if (true) return attributes;}
    throw new Error("Missing return statement in function");
  }

  final public Map<String,String> SetAttrValue(SequencePattern.Env env, Map<String,String> attributes) throws ParseException {
        Token attr = null;
        Token value = null;
        String str = null;
    attr = jj_consume_token(IDENTIFIER);
    jj_consume_token(23);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case STR:
    case BARESTR:
      value = RelaxedStringToken();
      break;
    case NONNEGINT:
    case INT:
    case REAL:
      value = NumberToken();
      break;
    default:
      jj_la1[43] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
              if (value != null) { str = value.image; }
              if (attr != null && str != null)  {
                if (attributes.containsKey(attr.image)) {
                {if (true) throw new Error("Attribute already defined: " + attr.image);}
                }
                attributes.put(attr.image, str);
              }
          {if (true) return attributes;}
    throw new Error("Missing return statement in function");
  }

  final public Token NumberToken() throws ParseException {
   Token value = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NONNEGINT:
      value = jj_consume_token(NONNEGINT);
      break;
    case INT:
      value = jj_consume_token(INT);
      break;
    case REAL:
      value = jj_consume_token(REAL);
      break;
    default:
      jj_la1[44] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return value;}
    throw new Error("Missing return statement in function");
  }

  final public Token IntegerToken() throws ParseException {
   Token value = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NONNEGINT:
      value = jj_consume_token(NONNEGINT);
      break;
    case INT:
      value = jj_consume_token(INT);
      break;
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return value;}
    throw new Error("Missing return statement in function");
  }

  final public Token RelaxedStringToken() throws ParseException {
   Token value = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STR:
      value = jj_consume_token(STR);
      break;
    case BARESTR:
      value = jj_consume_token(BARESTR);
      break;
    case IDENTIFIER:
      value = jj_consume_token(IDENTIFIER);
      break;
    default:
      jj_la1[46] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return value;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(25)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(39)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(REGEXVAR)) return true;
    return false;
  }

  private boolean jj_3R_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(15)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(7)) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(18)) return true;
    if (jj_scan_token(22)) return true;
    return false;
  }

  private boolean jj_3R_15() {
    Token xsp;
    if (jj_3R_16()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_16()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(18)) return true;
    if (jj_scan_token(21)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(35)) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_scan_token(18)) return true;
    if (jj_scan_token(NONNEGINT)) return true;
    if (jj_scan_token(26)) return true;
    if (jj_scan_token(20)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(18)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(25)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(18)) return true;
    if (jj_scan_token(NONNEGINT)) return true;
    if (jj_scan_token(20)) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(36)) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(BACKREF)) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(18)) return true;
    if (jj_scan_token(NONNEGINT)) return true;
    if (jj_scan_token(26)) return true;
    if (jj_scan_token(20)) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_scan_token(18)) return true;
    if (jj_scan_token(NONNEGINT)) return true;
    if (jj_scan_token(20)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public TokenSequenceParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[47];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x40080,0x40080,0x1000000,0x4fb80,0x4000000,0x4fb80,0x4fb80,0x5000000,0x5000000,0xfb80,0x201c580,0xe0040000,0x201c580,0xe0000000,0x40000,0x40000000,0x0,0x0,0x0,0x40000000,0x40000000,0x0,0x205c180,0x0,0x0,0x0,0x0,0x205c180,0x5c180,0x5000000,0x5000000,0x1c080,0x5c080,0x5c180,0x1c180,0x3900,0x10020000,0x1c080,0x40000,0x40000,0x80000,0x5000000,0x5000000,0x1b880,0x3800,0x1800,0x18080,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x88,0x0,0x88,0x0,0x0,0x0,0x1,0x3,0x3,0x4,0x4,0x8,0x28,0x1,0x2,0x3,0x3,0x20,0x20,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[9];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public TokenSequenceParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public TokenSequenceParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new TokenSequenceParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public TokenSequenceParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new TokenSequenceParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public TokenSequenceParser(TokenSequenceParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(TokenSequenceParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[41];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 47; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 41; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 9; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
