/* Generated By:JavaCC: Do not edit this line. TokenSequenceParserConstants.java */
package edu.stanford.nlp.ling.tokensregex;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface TokenSequenceParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 7;
  /** RegularExpression Id. */
  int REGEXVAR = 8;
  /** RegularExpression Id. */
  int REGEXGROUP = 9;
  /** RegularExpression Id. */
  int BACKREF = 10;
  /** RegularExpression Id. */
  int NONNEGINT = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int REAL = 13;
  /** RegularExpression Id. */
  int REGEX = 14;
  /** RegularExpression Id. */
  int STR = 15;
  /** RegularExpression Id. */
  int BARESTR = 16;
  /** RegularExpression Id. */
  int NUMCMP = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<IDENTIFIER>",
    "<REGEXVAR>",
    "<REGEXGROUP>",
    "<BACKREF>",
    "<NONNEGINT>",
    "<INT>",
    "<REAL>",
    "<REGEX>",
    "<STR>",
    "<BARESTR>",
    "<NUMCMP>",
    "\"{\"",
    "\"=>\"",
    "\"}\"",
    "\"tokens:\"",
    "\"text:\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\":\"",
    "\"*\"",
    "\"?\"",
    "\"+\"",
    "\"|\"",
    "\"&\"",
    "\"?:\"",
    "\"[\"",
    "\"]\"",
    "\"!\"",
    "\"#\"",
    "\"(?m)\"",
    "\"&annotate\"",
  };

}
